#5 add detail page
if-mentor/next_todo_6 pull request #26
Opened 2022-07-22 00:13 UTC by taisei78

## issueのURL
#5 

## 変更内容・変更理由
詳細ページの作成

## やってないこと・できていないこと
機能

## UI before / after
after 
https://gyazo.com/aeb675113c76241d24c944fb1e2e26ba

## 補足
見た目のみ作ってみました。見た目やモジュールの構成で間違っていたら申し訳ないです。

2022-07-22 00:22 UTC, hiromichi-code approved these changes, later dismissed

2022-07-22 00:38 UTC, k98a73 submitted a review, later dismissed
Title上の余白とCreateやEditと日時の間隔がFigmaより大きい様に感じます。
機能追加の際にでも修正してみてください。
![LGTM](https://image.lgtmoon.dev/121361)

2022-07-22 12:32 UTC, washogo requested changes
@taisei78 
画面表示は全体的に綺麗に整っていてgoodです！
デザインのように下に余白ができるようにしてみましょう！
<img width="908" alt="スクリーンショット 2022-07-22 21 30 03" src="https://user-images.githubusercontent.com/89339695/180439651-a78342e7-8140-458f-93c6-59c60dbb86f9.png">

2022-07-22 13:45 UTC, washogo requested changes
追記しました！

2022-07-22 13:45 UTC, washogo commented on pages/showPage/index.tsx
> +            </Box>
Inputはセルフクロージングで良いと思います！

2022-07-22 13:45 UTC, washogo commented on pages/showPage/index.tsx
> +            <HStack spacing="60px" p="10px" pb="20px">
Textareaはセルフクロージングで良いかと思います！

2022-07-22 13:45 UTC, washogo commented on pages/showPage/index.tsx
> +          <Box
Textはセルフクロージングで良いかと思います！

2022-07-22 23:30 UTC, taisei78 commented on pages/showPage/index.tsx
> +            </Box>
inputタグはセルフクロージングにしました。

2022-07-22 23:31 UTC, taisei78 commented on pages/showPage/index.tsx
> +            <HStack spacing="60px" p="10px" pb="20px">
Textareaタグはセルフクロージングにしました

2022-07-22 23:31 UTC, taisei78 commented on pages/showPage/index.tsx
> +          <Box
Textはセルフクロージングできますか？

2022-07-22 23:34 UTC, taisei78 commented
@washogo レビュー内容を修正しました。
ご確認お願いします。
(https://github.com/if-mentor/next_todo_6/pull/26/commits/99bc457f532b7164bfaafdff8226365aa79c3a57)

2022-07-22 23:48 UTC, taisei78 commented
@k98a73 レビュー内容を修正しました。
ご確認お願いします。
https://github.com/if-mentor/next_todo_6/pull/26/commits/4217fa648677e878bf045a846f52b0fdd4978221

2022-07-23 00:28 UTC, k98a73 commented
![LGTM](https://image.lgtmoon.dev/174858)

2022-07-23 00:40 UTC, washogo commented on pages/showPage/index.tsx
> +          <Box
@taisei78 
こちらボケてました、、すみません🙇‍♂️セルフクロージングできないので、そのままでお願いします！

2022-07-23 04:22 UTC, washogo approved these changes

2022-07-23 04:55 UTC, k98a73 approved these changes

2022-07-23 08:31 UTC, merged