#4 todo edit layout
if-mentor/next_todo_6 pull request #27
Opened 2022-07-22 02:04 UTC by k98a73

## issueのURL
[編集ページ #4](https://github.com/if-mentor/next_todo_6/issues/4)

## 変更内容・変更理由
Todo編集画面のレイアウト作成

## やったこと
- Todo編集画面のレイアウト作成
- Todo作成画面のHead修正及びレスポンシブ対応

## やってないこと・できていないこと
編集機能

## UI before / after
- before：真っ白なので省略
- after
[![Image from Gyazo](https://i.gyazo.com/01ca29545f5563d67a0218afac5ee50d.png)](https://gyazo.com/01ca29545f5563d67a0218afac5ee50d)

## テスト（ブラウザかコードでの動作確認）
レイアウト作成のみなので、省略

## レビュー観点
あくまで目安です。

- [ ] 想定通りに動作するか？
- [ ] より良いJS/JSX/TS/TSX/CSS/Reactの書き方はないか？
- [ ] 他の部分と書き方・命名・ディレクトリ構成等が異なっていないか？
- [ ] 関数、コンポーネントの粒度は適切か？（大き過ぎる、細かすぎる）
- [ ] より良い設計方法はないか？
- [ ] etc...

## 補足
特になし

2022-07-22 12:44 UTC, washogo requested changes
@k98a73 
デザインはとってもいい感じだと思います！

2022-07-22 12:44 UTC, washogo commented on pages/todoEdit.tsx
> +        <VStack>
paddingは0なら記載なくても大丈夫と思います！

2022-07-22 12:44 UTC, washogo commented on pages/todoEdit.tsx
> +              fontSize="24px"
marginは0なら記載しなくても大丈夫と思います！

2022-07-22 12:44 UTC, washogo commented on pages/todoEdit.tsx
> +              fontSize="24px"
marginはtopだけならmtの方が見やすいです！

2022-07-22 12:44 UTC, washogo commented on pages/todoEdit.tsx
> +              fontWeight="bold"
こちらのpaddingも同様と思います！

2022-07-22 12:50 UTC, washogo requested changes
追記しました〜

2022-07-22 12:50 UTC, washogo commented on pages/create.tsx
> +          </FormControl>
Inputはセルフクロージングで良いかと思います！

2022-07-22 12:50 UTC, washogo commented on pages/create.tsx
> +          <Flex w="100%">
paddingは0なら記載しなくて良いと思います！

2022-07-22 12:50 UTC, washogo commented on pages/create.tsx
> +              fontWeight="bold"
marginは0なら記載なくても良いと思います！

2022-07-22 12:50 UTC, washogo commented on pages/todoEdit.tsx
> +          </FormControl>
Inputはセルフクロージングの方が良いと思います！

2022-07-22 12:50 UTC, washogo commented on pages/todoEdit.tsx
> +          <Flex w="100%">
Textareaもセルフクロージングで良いかと思います！

2022-07-22 22:40 UTC, taisei78 approved these changes, later dismissed

2022-07-23 00:43 UTC, k98a73 commented on pages/todoEdit.tsx
> +        <VStack>
`Container`には左右の`padding`が16px含まれています。

[![Image from Gyazo](https://i.gyazo.com/776f91bde95e4813ddec8567b8b8123e.png)](https://gyazo.com/776f91bde95e4813ddec8567b8b8123e)

それを打ち消すために`p="0"`を入れていますが、消した方がよろしいでしょうか？

2022-07-23 00:49 UTC, k98a73 commented on pages/todoEdit.tsx
> +              fontSize="24px"
`FormLabel`には`margin-right: 12px`と`margin-bottom: 8px`が含まれています。

[![Image from Gyazo](https://i.gyazo.com/3e481f225d74ee7e63b57ee0a587baf1.png)](https://gyazo.com/3e481f225d74ee7e63b57ee0a587baf1)

それを打ち消すために`m="0"`を入れていますが、消した方がよろしいでしょうか？

2022-07-23 00:53 UTC, k98a73 commented on pages/todoEdit.tsx
> +              fontSize="24px"
`FormLabel`には`margin-right: 12px`と`margin-bottom: 8px`が含まれています。

[![Image from Gyazo](https://i.gyazo.com/cc03372f4345a45417c28b1c6e05620d.png)](https://gyazo.com/cc03372f4345a45417c28b1c6e05620d)

それを打ち消すために`m="8px 0 0 0"`としていますが、`mt="8px`とした方がよろしいでしょうか？

2022-07-23 00:56 UTC, k98a73 commented on pages/todoEdit.tsx
> +              fontWeight="bold"
`Button`には左右の`padding`が16px含まれています。

[![Image from Gyazo](https://i.gyazo.com/822379e34aee14d1ad8de0d9ad5d11b5.png)](https://gyazo.com/822379e34aee14d1ad8de0d9ad5d11b5)

それを打ち消すために`p="0"`を入れていますが、消した方がよろしいでしょうか？

2022-07-23 01:01 UTC, k98a73 commented on pages/create.tsx
> +          <Flex w="100%">
`Container`には左右の`padding`が16px含まれています。

[![Image from Gyazo](https://i.gyazo.com/e1ecd437aada12d1b7f457c1ebafd712.png)](https://gyazo.com/e1ecd437aada12d1b7f457c1ebafd712)

それを打ち消すために`p="0"`を入れていますが、消した方がよろしいでしょうか？

2022-07-23 01:03 UTC, k98a73 commented on pages/create.tsx
> +              fontWeight="bold"
`FormLabel`には`margin-right: 12px`と`margin-bottom: 8px`が含まれています。

[![Image from Gyazo](https://i.gyazo.com/e7e111d345b5d1d754aa336ea15ceb5e.png)](https://gyazo.com/e7e111d345b5d1d754aa336ea15ceb5e)

それを打ち消すために`m="0"`を入れていますが、消した方がよろしいでしょうか？

2022-07-23 01:10 UTC, k98a73 commented on pages/create.tsx
> +          </FormControl>
ご指摘ありがとうございます。
修正しました。
https://github.com/if-mentor/next_todo_6/pull/27/commits/ab55d7d850fd74c0ea3c198d0e661108493738ee

2022-07-23 01:11 UTC, k98a73 commented on pages/todoEdit.tsx
> +          </FormControl>
ご指摘ありがとうございます。
修正しました。
https://github.com/if-mentor/next_todo_6/pull/27/commits/cd97924833a38aecc00274ced554983181f98d5b

2022-07-23 01:11 UTC, k98a73 commented on pages/todoEdit.tsx
> +          <Flex w="100%">
ご指摘ありがとうございます。
修正しました。
https://github.com/if-mentor/next_todo_6/pull/27/commits/cd97924833a38aecc00274ced554983181f98d5b

2022-07-23 04:20 UTC, washogo approved these changes

2022-07-23 08:32 UTC, hiromichi-code approved these changes

2022-07-23 08:32 UTC, merged