#45 add: Dateをフォーマットするカスタムフックの導入
if-mentor/next_todo_6 pull request #46
Opened 2022-08-03 06:10 UTC by k98a73

## issueのURL
- #45

## 変更内容・変更理由
- `new Date()`をフォーマットする関数作成
- Todo NewのcreateAtにフォーマットした値を代入し、updateAtを追加

## やったこと
- Dateをyyyy-mm-dd hh:mm形式にフォーマットする関数を作成
- Todo NewのcreateAtの型を`null | Date`→`null | string`に変更
- Todo NewにupdateAtを追加

## やってないこと・できていないこと
特に無し

## UI before / after
変更無し

## テスト（ブラウザかコードでの動作確認）
- `CREATE`を押すとcreateAtに、フォーマットされた現在の日時がtodoListに保存される
- updateAtには""が保存されている
[![Image from Gyazo](https://i.gyazo.com/9e34e50c90653f7680e67eb9c962d73c.png)](https://gyazo.com/9e34e50c90653f7680e67eb9c962d73c)

## レビュー観点
あくまで目安です。

- [ ] 想定通りに動作するか？
- [ ] より良いJS/JSX/TS/TSX/CSS/Reactの書き方はないか？
- [ ] 他の部分と書き方・命名・ディレクトリ構成等が異なっていないか？
- [ ] 関数、コンポーネントの粒度は適切か？（大き過ぎる、細かすぎる）
- [ ] より良い設計方法はないか？
- [ ] etc...

## 補足
特に無し

2022-08-04 00:00 UTC, taisei78 approved these changes, later dismissed

2022-08-04 13:40 UTC, washogo requested changes
[React公式](https://ja.reactjs.org/docs/hooks-custom.html#:~:text=%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%95%E3%83%83%E3%82%AF%E3%81%A8%E3%81%AF%E3%80%81%E5%90%8D%E5%89%8D%E3%81%8C%20%E2%80%9Duse%E2%80%9D%20%E3%81%A7%E5%A7%8B%E3%81%BE%E3%82%8A%E3%80%81%E3%81%BB%E3%81%8B%E3%81%AE%E3%83%95%E3%83%83%E3%82%AF%E3%82%92%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%9B%E3%82%8B%20JavaScript%20%E3%81%AE%E9%96%A2%E6%95%B0%E3%81%AE%E3%81%93%E3%81%A8%E3%81%A7%E3%81%99%E3%80%82)より
```
カスタムフックとは、名前が ”use” で始まり、ほかのフックを呼び出せる JavaScript の関数のことです。
```
であるので、こちらを汎用的な関数として作成するなら、カスタムフックではなく、utilフォルダ内とかにchangeDateFormatとかにしてメソッドを定義する方が良きと思います！
下記の記事も参考にしてください。
https://qiita.com/cheez921/items/af5878b0c6db376dbaf0

2022-08-05 22:15 UTC, hiromichi-code approved these changes, later dismissed

2022-08-06 02:31 UTC, k98a73 commented
フォルダ名とファイル名を変更しました。

2022-08-06 04:24 UTC, washogo commented
![image](https://user-images.githubusercontent.com/89339695/183233643-001718db-b7d8-4c34-b72a-f94c2d433e6a.png)

2022-08-06 04:25 UTC, washogo approved these changes

2022-08-07 12:22 UTC, hiromichi-code approved these changes

2022-08-08 04:03 UTC, merged